import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { OptionsProvider } from "@/context/optionContext";
import { DataProvider } from "@/context/dataContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-100`} suppressHydrationWarning={true}>
        <DataProvider>
          <OptionsProvider>
            {children}
          </OptionsProvider>
        </DataProvider>
      </body>
    </html>
  );
}
